---
title: "Taller 2 - Visualizaci칩n y Exploraci칩n de bases de datos"
author: " Henry Carvajal (201718787),Julian Delgado (201712798) , Mariana Villabona (201816559)"
date: "Visualizaci칩n y Exploraci칩n de datos para ciencias sociales"
output: html_document
---

```{r Setup, include=FALSE}
# --- Limpiar entorno
rm(list = ls())
gc()
closeAllConnections()

# --- Cargar librer칤as necesarias
library("pacman")
require("pacman")
p_load( tidyverse, data.table, lubridate, readxl, ggthemes, plotly, janitor,ggplot2,openxlsx, writexl,stringi, patchwork, skimr,tidyverse, readxl, ggthemes, plotly,sf,osmdata,dplyr)

# --- Definir rutas
user <- Sys.getenv("USERNAME")

if (user == "judel") {
  path <- file.path("C:/Users", "judel", "OneDrive", "Documentos", 
                    "ANDES", "Semestre 3", "Visualizacion de datos", "Actividad 2")
} else if (user == "mvill") {
  path <- file.path("C:/Users", "mvill", "OneDrive", "Transitorio", "OneDrive", 
                    "Documentos", "GitHub", "Visualizaci-n-UniAndes","Taller 2")
} else if (user == "hncar") {
  path <- file.path("C:/Users", "hncar", "Documents", "GitHub", "Visualizaci-n-UniAndes", "Taller 2")
} else {
  path <- choose.dir(caption = "Selecciona la carpeta con los archivos")
}

setwd(path)


# --- Cargar datos 
data <- file.path(path, "data/2025 JNA VP.xlsx")


data_migracion_hogares  <- read_excel(data, sheet = "Hogares") %>% clean_names()
data_migracion_personas <- read_excel(data, sheet = "Personas") %>% clean_names()
```

# Limpieza b치sica
```{r Ajuste texto}
limpiar_texto <- function(df) {
  df[] <- lapply(df, function(x) {
    if (is.character(x) | is.factor(x)) {
      x <- tolower(as.character(x))                        # pasar a min칰sculas
      x <- stri_trans_general(x, "Latin-ASCII")            # quitar tildes
      return(x)
    } else {
      return(x)  # dejar igual las variables que no son texto
    }
  })
  return(as.data.frame(df))
}

# --- Aplicar a tus bases
data_migracion_hogares  <- limpiar_texto(data_migracion_hogares)
data_migracion_personas <- limpiar_texto(data_migracion_personas)
```

```{r Union bases}
data_migracion <- data_migracion_hogares %>%
  left_join(data_migracion_personas, by = "id_hogar")
```

## Exploraci칩n y creaci칩n de variables latentes
```{r A. ELIGIBILIDAD }
##############################################
# EDAD Y SEXO 
##############################################

# Histograma Sexo
data_migracion$sexo_desagregado <- ifelse(data_migracion$demo2 == "Otro",
                                    "Otros",
                                    "Sexo biol칩gico")

ggplot(data_migracion, aes(x = demo1)) +
  geom_histogram(bins = 20, fill = "steelblue", alpha = 0.7) +
  facet_wrap(~ sexo_desagregado + demo2, scales = "free_y") +
  labs(title = "Histograma de edad desagregado",
       x = "Edad", y = "Cuenta") +
  theme_minimal()

# Densidad por sexo y edad
ggplot(data_migracion, aes(x = demo1, fill = demo2)) +
  geom_density(alpha = 0.5) +
  labs(title = "Densidad de Edad por Sexo",
       x = "Edad",
       y = "Densidad") +
  theme_minimal()

# Probabilidades por edades
breaks <- pretty(range(data_migracion$demo1, na.rm = TRUE), n = 20)
dens_bins <- data_migracion %>%
  mutate(bin = cut(demo1, breaks = breaks, include.lowest = TRUE)) %>%
  group_by(demo2, bin) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(demo2) %>%
  mutate(freq = n / sum(n))  

# Rangos de edades 
data_migracion$rangos_edades <- cut(
  data_migracion$demo1,
  breaks = c(15, 25, 40, 70, Inf),
  labels = c("Joven", "Adulto Joven", "Adulto", "Adulto Mayor"),
  right = TRUE, include.lowest = TRUE
)
rm(dens_bins,breaks)

##############################################
# JEFES DE HOGAR 
##############################################
data_migracion %>%
  count(demo3) # Hay 8603 personas que reportan ser jefes de hogar

data_migracion %>%
  filter(!is.na(demo3) & demo3 != "") %>%
  count(demo5) # Todas las personas que no son jefes de hogar dicen poder
               # Responder por los miembros del hogar, coincide con                     # hogares sin jefes de hogar

# Identificar hogares sin jefes de hogar
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(no_tiene_jefe = as.integer(all(demo3 != "si" | is.na(demo3)))) %>%
  ungroup()

data_migracion %>%
  distinct(id_hogar, intro5, no_tiene_jefe) %>%
  group_by(intro5) %>%
  summarise(
    hogares_sin_jefe = sum(no_tiene_jefe),
    hogares_total = n(),
    porcentaje_sin_jefe = round(100 * hogares_sin_jefe / hogares_total, 1)
  ) %>%
  arrange(desc(hogares_sin_jefe)) # Resumen por ciudad

# Contar qui칠n se puede reasignar c칩mo jefe de hogar. 
resumen_por_ciudad <- data_migracion %>%
  filter(no_tiene_jefe == 1) %>%                      
  group_by(intro5, id_hogar) %>%
  summarise(
    Puede_responder_por_el_hogar = any(demo5 == "si", na.rm = TRUE),    
    Total_s칤 = sum(demo5 == "si", na.rm = TRUE),    
    Total_miembros_promedio_por_hogar = n(),                                  # n칰mero de personas en ese hogar
    .groups = "drop"
  ) %>%
  group_by(intro5) %>%
  summarise(
    hogares_sin_jefe = n(),   
    hogares_con_al_menos_un_s칤 = sum(Puede_responder_por_el_hogar),  
    promedio_s칤_por_hogar = round(mean(Total_s칤), 2),
    miembros_promedio = round(mean(Total_miembros_promedio_por_hogar), 2),    # promedio de miembros por hogar
    .groups = "drop"
  ) %>%
  arrange(desc(hogares_sin_jefe)) # En todos los hogares sin jefe de hogar
                                  # los miembros reportan que pueden responder                                   # por el resto. Por lo que se asigna                                          # aleatoriamente a cualquier integrante 
                                  # c칩mo jefe de hogar. 
resumen_por_ciudad
rm(resumen_por_ciudad)

# Asignar un jefe de hogar
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    demo3 = ifelse(no_tiene_jefe == 1 & row_number() == 1, "si", demo3)
  ) %>%
  ungroup()

##############################################
# INTENCI칍N DE MOVERSE
##############################################
intencion_moverse <- data_migracion %>%
  pivot_longer(
    cols = c(demo21_ing_red,
             demo21_suf_disc,
             demo21_aum_prec,
             demo21_desal_viv,
             demo21_no_alim,
             demo21_no_acces_sal,
             demo21_of_lab,
             demo21_acc_edu,
             demo21_acc_edu_nna,
             demo21_otro_inten),
    names_to = "variable",
    values_to = "valor"
  ) %>%
  group_by(intro5, variable) %>%
  summarise(n_1 = sum(valor == 1, na.rm = TRUE), .groups = "drop") %>%
  arrange(intro5, variable)

rm(intencion_moverse)

# Moverse por Falta de ingresos
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    carencia_ingresos = as.integer(any(
      demo21_ing_red == 1 | demo21_aum_prec == 1 | demo21_of_lab == 1,
      na.rm = TRUE
    ))
  ) %>% ungroup()

# Moverse por carencias de servicios (incluye educaci칩n y alimentaci칩n)
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    carencia_servicios = as.integer(any( demo21_no_alim == 1 | 
        demo21_no_acces_sal == 1| demo21_acc_edu == 1|
        demo21_acc_edu_nna ==1),
      na.rm = TRUE
    )) %>% ungroup()

# Moverse por discriminaci칩n (incluye desalojo)
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    discriminacion = as.integer(any(
      demo21_suf_disc == 1 ),
      na.rm = TRUE
    )) %>% ungroup()

##############################################
# A칌OS
##############################################
data_migracion <- data_migracion %>%
  mutate(
    fecha_demo8 = ymd(demo8),   # convertir string a fecha
    meses_transcurridos = interval(fecha_demo8, today()) %/% months(1),
    anios_en_Col = meses_transcurridos / 12
  )

```

```{r B. INTENSIONES Y MOVIMIENTOS }
#########################################
# MIGRAR EN PR칍XIMOS 6 MESES
#########################################
data_migracion <- data_migracion %>%
  mutate(
    `6M_sinmov`      = ifelse(demo22 == "no tienen la intencion de moverse", 1, 0), 
    `6M_Mudar_barrio`= ifelse(demo22 == "si, nos vamos a mudar de barrio al interior de esta ciudad", 1, 0),
    `6M_Depto`       = ifelse(demo22 == "si, nos vamos a cambiar a otro departamento al interior de colombia", 1, 0),
    `6M_Venezuela`   = ifelse(demo22 == "si, irnos a venezuela", 1, 0),
    `6M_OtroPais`    = ifelse(demo22 == "si, irnos a otro pais (diferente a venezuela)", 1, 0),
    `6M_MismoDpto`   = ifelse(demo22 == "si, nos vamos a cambiar de municipio pero en el mismo departamento actual", 1, 0)
  )

#########################################
# HACE CU츼NTO TIEMPO RESIDE EN EL HOGAR
#########################################
data_migracion <- data_migracion %>%
  mutate(
    meses_en_lugar = case_when(
      demo12a %in% c("no sabe", "prefiere no responder") ~ NA_character_,
      demo12a == "menos de 1 mes" ~ "<1",
      demo12a == "entre 1 mes y menos de 6 meses" ~ "1-6",
      demo12a == "entre 6 meses y menos de 1 ano" ~ "6-12",
      demo12a == "entre 1 ano y menos de 2 anos" ~ "12-24",
      demo12a == "entre 2 y menos de 3 anos" ~ "24-36",
      demo12a == "entre 3 y 10 anos" ~ "36-120",
      demo12a == "mas de 10 anos" ~ ">120",
      TRUE ~ NA_character_
    ),
    meses_en_lugar = factor(
      meses_en_lugar,
      levels = c("<1", "1-6", "6-12", "12-24", "24-36", "36-120", ">120"),
      ordered = TRUE
    )
  )

#########################################
# RAZ칍N POR LA QUE MIGR칍 A RESIDENCIA ACTUAL 
#########################################
data_migracion <- data_migracion %>%
  mutate(
    Migro_por_violencia = ifelse(demo17 %in% c(
      "la persona o alguien cercano fue victima 
      de violencia (extorsion, agresiones, etc.) o amenazas",
      "temor por la situacion general de violencia / inseguridad"), 1, 0),
    
    Migro_por_familia = ifelse(demo17 %in% c(
      "acompanar a otros miembros del hogar",
      "reunificacion familiar"), 1, 0),
    
    Migro_por_discriminacion = ifelse(demo17 %in% c(
      "salud mental o fisica",
      "temor de ser perseguido/a, agredido/a o discriminado/a"), 1, 0),
    
    Migro_por_trabajo = ifelse(demo17 == "trabajo", 1, 0),
    
    Migro_por_educacion = ifelse(demo17 == "educacion", 1, 0),
    
    Migro_por_des_natural = ifelse(demo17 == "desastres naturales", 1, 0),
    
    Migro_por_alimentos = ifelse(demo17 == "alimentos", 1, 0)
  )

```

```{r K. AGUA, SANEAMIENTO E HIGIENE (WASH)}
#########################################
# ACCESO A AGUA
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    Acueducto_casa = as.integer(any(wash1 == "agua de tuberia por grifo", na.rm = TRUE)),
    AguaPublica_fueradecasa = as.integer(any(
      wash1 %in% c("perforaciones / pozos tubulares (publicos)",
                   "pilas o fuentes publicas (fuentes publicas)"),
      na.rm = TRUE
    )),
    Agua_FuentesNaturales = as.integer(any(
      wash1 %in% c("agua de lluvia",
                   "agua superficial (rio, quebrada, manantial, lago)"),
      na.rm = TRUE
    )),
    Agua_FuentesPrivadas = as.integer(any(
      wash1 %in% c("agua envasada, agua embotellada y agua en bolsitas",
                   "de pozo sin bomba, aljibe, jaguey o barreno; (no protegido)",
                   "suministro de agua, incluidos camiones cisterna y carros / tanques / tambores pequenos"),
      na.rm = TRUE
    )),
    Agua_NoAcceso = as.integer(any(wash1 == "no tiene acceso", na.rm = TRUE))
  ) %>%
  ungroup()

#########################################
# AGUA EN VIVIENDA
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    Acceso_agua_casa = as.integer(any(wash01 == "si", na.rm = TRUE)),
    No_Acceso_agua_casa = as.integer(any(wash01 == "no", na.rm = TRUE)),
    Acceso_agua_casa_Otro = as.integer(any(wash01 %in% c("no sabe", "prefiere no responder"), na.rm = TRUE))
  ) %>%
  ungroup()

#########################################
# TIEMPO PARA AGUA 
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    Agua_caminar_largo = as.integer(any(wash3 == "mas de 30 minutos", na.rm = TRUE)),
    Agua_caminar_corto = as.integer(any(wash3 == "menos de 30 minutos", na.rm = TRUE))
  ) %>%
  ungroup()

#########################################
# SATISFACCI칍N NECESIDADES B츼SICAS AGUA
#########################################
data_migracion <- data_migracion %>%
  mutate(
    Agua_Satisfaccion = case_when(
      wash5 == "si" ~ 1L,
      wash5 == "no" ~ 0L,
      TRUE ~ NA_integer_
    )
  )

#########################################
# TIEMPO DE COBERTURA DEL SERVICIO 
#########################################
data_migracion <- data_migracion %>%
  mutate(
    Agua_CoberturaTotal = ifelse(
      wash6 == "las 24 horas del dia, los 7 dias de la semana", 1L, 0L
    ),
    Agua_CoberturaMedia = ifelse(
      wash6 %in% c("llega a diario pero solo a ciertas horas del 
                   dia/en horarios restringidos",
                   "las 24 horas de 4 a 6 dias a la semana"), 1L, 0L
    ),
    Agua_MalaCobertura = ifelse(
      wash6 %in% c("las 24 horas 1 a 2 dias a la semana",
                   "las 24 horas 3 dias a la semana"), 1L, 0L
    )
  )

#########################################
# INFORMACI칍N SANEAMIENTO 
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    # Calidad
    Saneamiento_deCalidad = as.integer(any(
      wash11 %in% c("inodoro conectado a alcantarillado",
                    "inodoro conectado a pozo septico"),
      na.rm = TRUE
    )),
    
    # No calidad
    Saneamiento_noCalidad = as.integer(any(
      wash11 %in% c("letrinas colgantes o inodoro con descarga directa a fuentes de agua (bajamar)",
                    "inodoro sin conexion (banos portatiles)",
                    "defecacion al aire libre",
                    "letrina de pozo con losa y plataforma",
                    "no tiene servicio sanitario, pero tiene un lugar gratuito y seguro",
                    "no tiene servicio sanitario y tiene que pagar el servicio",
                    "letrina improvisada"),
      na.rm = TRUE
    )),
    
    # Letrinas
    Saneamiento_Letrina = as.integer(any(
      wash11 %in% c("letrinas colgantes o inodoro con descarga directa a fuentes de agua (bajamar)",
                    "inodoro sin conexion (banos portatiles)",
                    "letrina de pozo con losa y plataforma",
                    "letrina improvisada"),
      na.rm = TRUE
    )),
    
    # Privado
    Saneamiento_Privado = as.integer(any(
      wash11 == "no tiene servicio sanitario y tiene que pagar el servicio",
      na.rm = TRUE
    )),
    
    # Uso p칰blico
    Saneamiento_UsoPublico = as.integer(any(
      wash11 %in% c("no tiene servicio sanitario, pero tiene un lugar gratuito y seguro",
                    "inodoro sin conexion (banos portatiles)"),
      na.rm = TRUE
    )),
    
    # Sin cobertura
    Saneamiento_SinCobertura = as.integer(any(
      wash11 %in% c("defecacion al aire libre",
                    "no tiene servicio sanitario, pero tiene un lugar gratuito y seguro",
                    "no tiene servicio sanitario y tiene que pagar el servicio"),
      na.rm = TRUE
    ))
  ) %>%
  ungroup()


#########################################
# SERVICIO DE BASURA
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    Servicio_basuraPublico = as.integer(any(
      wash17 == "camion de basura municipal/punto de acopio formal", 
      na.rm = TRUE
    )),
    
    Servicio_basuraPrivado = as.integer(any(
      wash17 == "servicio informal (punto de acopio no autorizado, recicladores/cartoneros)", 
      na.rm = TRUE
    )),
    
    Servicio_Nobasura = as.integer(any(
      wash17 %in% c("no sabe",
                    "la tiran en la calle, via publica y/o rio",
                    "la queman o entierran"),
      na.rm = TRUE
    ))) %>%
  ungroup()

#########################################
# AMBIENTE CONTAMINADO
#########################################
data_migracion <- data_migracion %>%
  group_by(id_hogar) %>%
  mutate(
    AmbienteContaminado = as.integer(any(
      wash17 %in% c("la tiran en la calle, via publica y/o rio",
                    "la queman o entierran") |
      wash11 %in% c("defecacion al aire libre",
                    "letrinas colgantes o inodoro con descarga directa a fuentes de agua (bajamar)"),
      na.rm = TRUE
    ))
  ) %>%
  ungroup()

#########################################
# PRBLEMAS PARA ACCEDER A ART칈CULOS DE HIGIENE 
#########################################
data_migracion <- data_migracion %>%
  mutate(
    wash20 = factor(
      wash20,
      levels = c("no (falta de jabon, lavamanos con agua)",
                 "si",
                 "utilizo gel antibacterial / toallas humedas / alcohol"),
      labels = c("No (falta de jab칩n/agua)", "S칤", "Gel/Toallas/Alcohol"),
      ordered = TRUE
    )
  )
```

Se prioriza el registro del jefe de hogar en caso de no existir se escoje otro
## Exploraci칩n y creaci칩n de variables latentes

```{r Estad칤sticas descriptivas}
# Intenci칩n de migrar en 6 meses
resumen_intencion_6M <- data_migracion %>%
  group_by(intro5) %>%
  summarise(
    sinmov = sum(`6M_sinmov`, na.rm = TRUE),
    mudar_barrio = sum(`6M_Mudar_barrio`, na.rm = TRUE),
    depto = sum(`6M_Depto`, na.rm = TRUE),
    venezuela = sum(`6M_Venezuela`, na.rm = TRUE),
    otro_pais = sum(`6M_OtroPais`, na.rm = TRUE),
    mismo_dpto = sum(`6M_MismoDpto`, na.rm = TRUE),
    .groups = "drop"
  )
resumen_intencion_6M


# Tiempo de residencia en lugar en que se encuentra actualmente
resumen_meses_lugar <- data_migracion %>%
  group_by(intro5, meses_en_lugar) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(intro5) %>%
  mutate(
    pct = round(100 * n / sum(n), 1)   # porcentaje dentro de cada ciudad
  ) %>%
  arrange(intro5, meses_en_lugar)
resumen_meses_lugar

# Motivo por el que migr칩 a residencia actual 
resumen_motivos <- data_migracion %>%
  group_by(intro5) %>%
  summarise(
    violencia      = sum(Migro_por_violencia, na.rm = TRUE),
    familia        = sum(Migro_por_familia, na.rm = TRUE),
    discriminacion = sum(Migro_por_discriminacion, na.rm = TRUE),
    trabajo        = sum(Migro_por_trabajo, na.rm = TRUE),
    educacion      = sum(Migro_por_educacion, na.rm = TRUE),
    des_natural    = sum(Migro_por_des_natural, na.rm = TRUE),
    alimentos      = sum(Migro_por_alimentos, na.rm = TRUE),
    .groups = "drop"
  )
# ACCESO A AGUA
resumen_agua <- data_migracion %>%
  distinct(id_hogar, intro5, Acueducto_casa, AguaPublica_fueradecasa,
           Agua_FuentesNaturales, Agua_FuentesPrivadas, Agua_NoAcceso) %>%
  group_by(intro5) %>%
  summarise(
    hogares_con_Acueducto = sum(Acueducto_casa, na.rm = TRUE),
    hogares_con_AguaPublica_fuera = sum(AguaPublica_fueradecasa, na.rm = TRUE),
    hogares_con_AguaNatural = sum(Agua_FuentesNaturales, na.rm = TRUE),
    hogares_con_AguaPrivada = sum(Agua_FuentesPrivadas, na.rm = TRUE),
    hogares_sin_Agua = sum(Agua_NoAcceso, na.rm = TRUE),
    total_hogares = n(),
    .groups = "drop"
  ) %>%
  mutate(
    pct_Acueducto = round(100 * hogares_con_Acueducto / total_hogares, 1),
    pct_AguaPublica_fuera = round(100 * hogares_con_AguaPublica_fuera / total_hogares, 1),
    pct_AguaNatural = round(100 * hogares_con_AguaNatural / total_hogares, 1),
    pct_AguaPrivada = round(100 * hogares_con_AguaPrivada / total_hogares, 1),
    pct_NoAcceso = round(100 * hogares_sin_Agua / total_hogares, 1)
  )

# CAMINAR PARA ACCEDER A AGUA (CORTO < 30 MIN, LARGO > 30 MIN)
resumen_caminar <- data_migracion %>%
  distinct(id_hogar, intro5, Agua_caminar_largo, Agua_caminar_corto) %>%
  group_by(intro5) %>%
  summarise(
    hogares_largo = sum(Agua_caminar_largo, na.rm = TRUE),
    hogares_corto = sum(Agua_caminar_corto, na.rm = TRUE),
    total_hogares = n(),
    .groups = "drop"
  ) %>%
  mutate(
    pct_largo = round(100 * hogares_largo / total_hogares, 1),
    pct_corto = round(100 * hogares_corto / total_hogares, 1)
  ) %>%
  arrange(desc(total_hogares))
resumen_caminar


# ACCESO A SANEAMIENTO
resumen_saneamiento <- data_migracion %>%
  distinct(id_hogar, intro5, 
           Saneamiento_deCalidad, Saneamiento_noCalidad, 
           Saneamiento_Letrina, Saneamiento_Privado, 
           Saneamiento_UsoPublico, Saneamiento_SinCobertura) %>%
  group_by(intro5) %>%
  summarise(
    hogares_deCalidad     = sum(Saneamiento_deCalidad, na.rm = TRUE),
    hogares_noCalidad     = sum(Saneamiento_noCalidad, na.rm = TRUE),
    hogares_Letrina       = sum(Saneamiento_Letrina, na.rm = TRUE),
    hogares_Privado       = sum(Saneamiento_Privado, na.rm = TRUE),
    hogares_UsoPublico    = sum(Saneamiento_UsoPublico, na.rm = TRUE),
    hogares_SinCobertura  = sum(Saneamiento_SinCobertura, na.rm = TRUE),
    total_hogares         = n(),
    .groups = "drop"
  ) %>%
  mutate(
    pct_deCalidad    = round(100 * hogares_deCalidad / total_hogares, 1),
    pct_noCalidad    = round(100 * hogares_noCalidad / total_hogares, 1),
    pct_Letrina      = round(100 * hogares_Letrina / total_hogares, 1),
    pct_Privado      = round(100 * hogares_Privado / total_hogares, 1),
    pct_UsoPublico   = round(100 * hogares_UsoPublico / total_hogares, 1),
    pct_SinCobertura = round(100 * hogares_SinCobertura / total_hogares, 1)
  ) %>%
  arrange(desc(total_hogares))
resumen_saneamiento
```

## Cortar base a nivel de observaci칩n de inter칠s

```{r Filtro ciudad y creacion variable hacinamiento}
# --- Filtrar Bogot치
data_bogota <- data_migracion %>%
  filter(intro5 == "bogota. d.c.")

# --- Quedarse con un registro por hogar, prefiriendo demo3 == "si"
data_filtrada <- data_bogota %>%
  group_by(id_hogar) %>%
  arrange(desc(demo3 == "si")) %>%  # ordena poniendo primero los que tienen demo3 == "si"
  slice(1) %>%                      # toma el primer registro de cada hogar
  ungroup()

# --- Calcular 칤ndice de hacinamiento
data_filtrada <- data_filtrada %>%
  mutate(
    personas_cuarto = miembros1 / alojamiento7,
    hacinamiento = case_when(
      is.na(personas_cuarto) ~ NA_character_,
      personas_cuarto <= 2 ~ "Sin hacinamiento",
      personas_cuarto > 2 & personas_cuarto <= 3 ~ "Moderado",
      personas_cuarto > 3 ~ "Cr칤tico"
    )
  )
```

```{r Filtro Jefe de hogar}
# Variables 칰nicas (riesgo desalojo, intenci칩n moverse, tiempo residencia)
vars_unica <- c("miembros1", "alojamiento7")
```

```{r NA}
# --- NA en variables 칰nicas
na_resumen <- sapply(data_filtrada[vars_unica], function(x) sum(is.na(x)))
na_resumen
```
```{r distribucion hacinamiento}
table(data_filtrada$hacinamiento, useNA = "ifany")
```
```{r distribucion hacinamiento}
# Orden l칩gico de categor칤as
data_filtrada$hacinamiento <- factor(
  data_filtrada$hacinamiento,
  levels = c("Sin hacinamiento", "Moderado", "Cr칤tico")
)

# Gr치fico de barras
ggplot(data_filtrada, aes(x = hacinamiento, fill = hacinamiento)) +
  geom_bar() +
  theme_minimal() +
  labs(
    title = "Distribuci칩n del hacinamiento en Bogot치",
    x = "Categor칤a de hacinamiento",
    y = "N칰mero de hogares"
  ) +
  theme(legend.position = "none")
```
```{r distribucion hacinamiento}
hacinamiento_resumen <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(Frecuencia = n()) %>%
  mutate(Proporcion = round(100 * Frecuencia / sum(Frecuencia), 1))

hacinamiento_resumen
```

```{r comparacion variables de interes}
table(data_filtrada$hacinamiento, data_filtrada$demo22, useNA = "ifany")
```

```{r comparacion variables de medios de vida}
vars_financieras <- c(
  # Fuentes de ingreso
  "mediosvida5_mediosvida5_prestamos",
  "mediosvida5_mediosvida5_ahorros",
  "mediosvida5_mediosvida5_trabajo",
  "mediosvida5_mediosvida5_asistencia",
  "mediosvida5_mediosvida5_apoyocomunidad",
  "mediosvida5_mediosvida5_venderbienes",
  "mediosvida5_mediosvida5_donaciones",
  "mediosvida5_mediosvida5_notiene",  
  "mediosvida5_mediosvida5_otra",   
  
  # Productos financieros
  "mediosvida7_mediosvida7_cuenta_ahorro",
  "mediosvida7_mediosvida7_cuenta_corriente",
  "mediosvida7_mediosvida7_billetera_electronica",
  "mediosvida7_mediosvida7_deposito_bajo_monto",
  "mediosvida7_mediosvida7_microcredito",
  "mediosvida7_mediosvida7_prestamo_vivienda",
  "mediosvida7_mediosvida7_prestamo_de_libre_inversion",
  "mediosvida7_mediosvida7_tarjeta_de_credito",
  "mediosvida7_mediosvida7_otro",  
  "mediosvida7_mediosvida7_ninguno", 
  "mediosvida7_mediosvida7_no_sabe", 
  "mediosvida7_mediosvida7_noresponde"

)
```

```{r comparacion variables de medios de vida}
resumen_financieros <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(across(all_of(vars_financieras), ~ sum(. == "1", na.rm = TRUE))) 

resumen_financieros
```

```{r comparacion variables de medios de vida}
resumen_finanzas_largo <- resumen_financieros %>%
  pivot_longer(
    cols = -hacinamiento,
    names_to = "producto",
    values_to = "conteo"
  )



resumen_finanzas_largo <- resumen_finanzas_largo %>%
  mutate(producto = str_replace_all(producto,
                                    c("mediosvida5_" = "",
                                      "mediosvida7_" = "")))

head(resumen_finanzas_largo, 10)
```

```{r comparacion variables de medios de vida}
# --- Para MEDIOS DE VIDA 5 (fuentes de ingresos/dinero)
resumen_mv5 <- resumen_financieros %>%
  select(hacinamiento, starts_with("mediosvida5")) %>% 
  pivot_longer(
    cols = -hacinamiento,
    names_to = "producto",
    values_to = "conteo"
  ) %>%
  group_by(hacinamiento) %>%
  mutate(
    total = sum(conteo, na.rm = TRUE),
    porcentaje = round((conteo / total) * 100, 1),
    producto = gsub("mediosvida5_mediosvida5_", "", producto)  # limpiar nombres
  )

# --- Para MEDIOS DE VIDA 7 (productos financieros)
resumen_mv7 <- resumen_financieros %>%
  select(hacinamiento, starts_with("mediosvida7")) %>% 
  pivot_longer(
    cols = -hacinamiento,
    names_to = "producto",
    values_to = "conteo"
  ) %>%
  group_by(hacinamiento) %>%
  mutate(
    total = sum(conteo, na.rm = TRUE),
    porcentaje = round((conteo / total) * 100, 1),
    producto = gsub("mediosvida7_mediosvida7_", "", producto)  # limpiar nombres
  )
```

```{r comparacion variables de medios de vida}
# --- Gr치fico 1: Fuentes de ingresos (MV5)
ggplot(resumen_mv5, aes(x = hacinamiento, y = porcentaje, fill = producto)) +
  geom_col(position = "stack") +
  labs(
    title = "쮸ctualmente en su hogar cu치les son las principales fuentes de ingresos/dinero?",
    x = "Nivel de hacinamiento",
    y = "Porcentaje"
  ) +
  theme_minimal()
```
```{r comparacion variables de medios de vida}
# --- Gr치fico 2: Productos financieros (MV7)
ggplot(resumen_mv7, aes(x = hacinamiento, y = porcentaje, fill = producto)) +
  geom_col(position = "stack") +
  labs(
    title = "쯈u칠 tipo de productos financieros tiene su hogar actualmente en Colombia?",
    x = "Nivel de hacinamiento",
    y = "Porcentaje"
  ) +
  theme_minimal()
```

```{r comparacion variables de medios de vida}
# Total de hogares por categor칤a de hacinamiento
totales_hogares <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(total_hogares = n(), .groups = "drop")
```

```{r comparacion variables de medios de vida}
# --- Medios de vida 5 ---
resumen_mv5 <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(
    across(starts_with("mediosvida5_mediosvida5"), ~sum(. == "1", na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = -hacinamiento,
    names_to = "producto",
    values_to = "conteo"
  ) %>%
  left_join(totales_hogares, by = "hacinamiento") %>%
  mutate(
    porcentaje_hogares = round((conteo / total_hogares) * 100, 1),
    producto = str_remove(producto, "mediosvida5_mediosvida5_")
  )

```

```{r comparacion variables de medios de vida}
# --- Gr치fico Medios de Vida 5 (Ingresos) ---
resumen_mv5 %>%
  filter(!is.na(porcentaje_hogares), porcentaje_hogares > 0) %>%
  ggplot(aes(x = producto, y = porcentaje_hogares, fill = hacinamiento)) +
  geom_col(position = "dodge") +
  labs(
    title = "쮸ctualmente en su hogar cu치les son las principales fuentes de ingresos/dinero?",
    x = "Fuente de ingresos",
    y = "% de hogares"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r comparacion variables de medios de vida}
# --- Medios de vida 7 ---
resumen_mv7 <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(
    across(starts_with("mediosvida7_mediosvida7"), ~sum(. == "1", na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = -hacinamiento,
    names_to = "producto",
    values_to = "conteo"
  ) %>%
  left_join(totales_hogares, by = "hacinamiento") %>%
  mutate(
    porcentaje_hogares = round((conteo / total_hogares) * 100, 1),
    producto = str_remove(producto, "mediosvida7_mediosvida7_")
  )
```

```{r comparacion variables de medios de vida}
# --- Medios de vida 7 ---

# --- Gr치fico Medios de Vida 7 (Productos Financieros) ---
resumen_mv7 %>%
  filter(porcentaje_hogares > 0) %>%   # 游댳 Elimina categor칤as sin info
  ggplot(aes(x = producto, y = porcentaje_hogares, fill = hacinamiento)) +
  geom_col(position = "dodge") +
  labs(
    title = "쯈u칠 tipo de productos financieros tiene su hogar actualmente en Bogota?",
    x = "Producto financiero",
    y = "% de hogares"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r Problemas de vivienda}
preg_multi <- c("alojamiento3")

cols_multi <- names(data_filtrada)[str_detect(
  names(data_filtrada),
  paste0("^(", paste(preg_multi, collapse="|"), ")_")
)]
```

```{r Problemas de vivienda}
data_alojamiento3 <- data_filtrada %>%
  pivot_longer(
    cols = all_of(cols_multi),
    names_to = c("pregunta", "respuesta"),
    names_pattern = "([^_]+)_(.*)",
    values_to = "valor"
  ) %>%
  filter(valor == 1)%>%
  mutate(respuesta = str_remove(respuesta, "^alojamiento3_"))
```

```{r Problemas de vivienda}
resumen_aloj3 <- data_alojamiento3 %>%
  count(respuesta, name = "conteo") %>%
  arrange(desc(conteo))

resumen_aloj3

```

```{r Problemas de vivienda}
ggplot(resumen_aloj3, aes(x = reorder(respuesta, -conteo), y = conteo, fill = respuesta)) +
  geom_col() +
  theme_minimal() +
  labs(
    title = "Problemas relacionados con la vivienda y el entorno",
    x = "Tipo de problema reportado",
    y = "N칰mero de hogares"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

```

```{r Problemas de vivienda}
# Pasar a formato largo (solo respuestas marcadas = 1)
data_aloj3 <- data_filtrada %>%
  pivot_longer(
    cols = all_of(cols_multi),
    names_to = c("pregunta", "respuesta"),
    names_pattern = "([^_]+)_(.*)",
    values_to = "valor"
  ) %>%
  filter(valor == 1)
```

```{r Problemas de vivienda}
resumen_aloj3_menciones <- data_aloj3 %>%
  count(respuesta, name = "conteo") %>%
  arrange(desc(conteo))%>%
  mutate(respuesta = str_remove(respuesta, "^alojamiento3_"))

```

```{r Problemas de vivienda}
resumen_aloj3_hogar <- data_aloj3 %>%
  group_by(respuesta) %>%
  summarise(n_hogares = n_distinct(id_hogar), .groups = "drop")%>%
  mutate(respuesta = str_remove(respuesta, "^alojamiento3_"))

```

```{r Problemas de vivienda}
plot_aloj3_menciones <- ggplot(resumen_aloj3_menciones,
                               aes(x = respuesta, y = conteo, fill = respuesta)) +
  geom_col() +
  labs(title = "Problemas de vivienda (menciones)",
       x = "Problema reportado", y = "N칰mero de menciones") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")

plot_aloj3_hogar <- ggplot(resumen_aloj3_hogar,
                           aes(x = respuesta, y = n_hogares, fill = respuesta)) +
  geom_col() +
  labs(title = "Problemas de vivienda (hogares 칰nicos)",
       x = "Problema reportado", y = "N칰mero de hogares") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")

# Mostrar juntos
plot_aloj3_menciones + plot_aloj3_hogar

```


```{r Problemas de vivienda}
vars_entorno <- c(
  "alojamiento3_alojamiento3_no_conflic",
  "alojamiento3_alojamiento3_no_higiene",
  "alojamiento3_alojamiento3_no_lnfaestruc",
  "alojamiento3_alojamiento3_no_privacidad",
  "alojamiento3_alojamiento3_desastres",
  "alojamiento3_alojamiento3_ninguna",
  "alojamiento3_alojamiento3_otro"
  )
```

```{r Problemas de vivienda}
resumen_entorno <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(across(all_of(vars_entorno), ~ sum(. == "1", na.rm = TRUE))) 

resumen_entorno
```


```{r Problemas de vivienda}

resumen_aloj3_hacinamiento <- resumen_entorno %>%
  select(hacinamiento, starts_with("alojamiento3")) %>% 
  pivot_longer(
    cols = -hacinamiento,
    names_to = "problema",
    values_to = "conteo"
  ) %>%
  group_by(hacinamiento) %>%
  mutate(
    total = sum(conteo, na.rm = TRUE),
    porcentaje = round((conteo / total) * 100, 1),
    problema = gsub("alojamiento3_alojamiento3_", "", problema)  # limpiar nombres
  ) %>%
  left_join(totales_hogares, by = "hacinamiento") %>%
  mutate(
    porcentaje_hogares = round((conteo / total_hogares) * 100, 1),
    producto = str_remove(problema, "alojamiento3_alojamiento3_")
  )


# --- Gr치fico Problemas de vivienda ---
ggplot(resumen_aloj3_hacinamiento, aes(x = problema, y = porcentaje_hogares, fill = hacinamiento)) +
  geom_col(position = "dodge") +
  labs(
    title = "Problemas relacionados con la vivienda y el entorno",
    x = "Problema reportado",
    y = "% de hogares"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r Gasto en vivienda}
# Resumen de la variable de gasto en vivienda
summary(data_filtrada$san53_viv)

# Revisar cu치ntos NA hay
sum(is.na(data_filtrada$san53_viv))
```

```{r Gasto en vivienda}
# --- Resumen estad칤stico del gasto en vivienda
resumen_gasto_viv <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(
    n = n(),
    media = mean(san53_viv, na.rm = TRUE),
    mediana = median(san53_viv, na.rm = TRUE),
    p25 = quantile(san53_viv, 0.25, na.rm = TRUE),
    p75 = quantile(san53_viv, 0.75, na.rm = TRUE),
    maximo = max(san53_viv, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r Gasto en vivienda}
# --- Resumen estad칤stico del gasto en vivienda
print(resumen_gasto_viv) 
```

```{r Gasto en vivienda}
# --- Revisar NA en variables de gasto
colSums(is.na(data_filtrada[, c("san52_alim", "san53_viv", 
                                "san54_serv", "san55_sal", 
                                "san56_edu", "san57_otros")]))

# --- Revisar NA en gasto_total y pct_vivienda
sum(is.na(data_filtrada$gasto_total))
sum(is.na(data_filtrada$pct_vivienda))

# --- Proporci칩n de NA en pct_vivienda
mean(is.na(data_filtrada$pct_vivienda))
```

```{r Gasto en vivienda}
# --- Crear variable de gasto total
data_filtrada <- data_filtrada %>%
  mutate(
    gasto_total = rowSums(across(c(san52_alim, san53_viv, san54_serv,
                                   san55_sal, san56_edu, san57_otros)), na.rm = TRUE),
    pct_vivienda = if_else(gasto_total > 0, (san53_viv / gasto_total) * 100, NA_real_)
  )

# --- Revisar tabla de resumen
resumen_pct_viv <- data_filtrada %>%
  group_by(hacinamiento) %>%
  summarise(
    n = n(),
    media = mean(pct_vivienda, na.rm = TRUE),
    mediana = median(pct_vivienda, na.rm = TRUE),
    p25 = quantile(pct_vivienda, 0.25, na.rm = TRUE),
    p75 = quantile(pct_vivienda, 0.75, na.rm = TRUE),
    maximo = max(pct_vivienda, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r Gasto en vivienda}
print(resumen_pct_viv)
```

```{r Gasto en vivienda}
ggplot(data_filtrada, aes(x = hacinamiento, y = pct_vivienda, fill = hacinamiento)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  theme_minimal(base_size = 12) +
  labs(
    title = "Porcentaje del gasto total destinado a vivienda",
    x = "Nivel de hacinamiento",
    y = "% del gasto en vivienda"
  ) +
  scale_y_continuous(labels = percent_format(scale = 1)) +  # convierte a %
  theme(legend.position = "none")
```

## Segundo analisis a partir de dificultades a nivel hogar

```{r Filtro necesidades}
vars_necesidades <- c(
  "aap6a_aap6_empleo",
  "aap6a_aap6_alojamiento",
  "aap6a_aap6_comida",
  "aap6a_aap6_semillas",
  "aap6a_aap6_asistencia_tec",
  "aap6a_aap6_agua_med",
  "aap6a_aap6_articulos_hig",
  "aap6a_aap6_servicios_san",
  "aap6a_aap6_articulos_hog",
  "aap6a_aap6_educ",
  "aap6a_aap6_transporte",
  "aap6a_aap6_atencion_med",
  "aap6a_aap6_medicamentos",
  "aap6a_aap6_apoyo_psico",
  "aap6a_aap6_apoyo_psicolegal",
  "aap6a_aap6_deudas",
  "aap6a_aap6_comunicacion",
  "aap6a_aap6_otro",
  "aap6a_aap6_ninguno",
  "aap6a_aap6_nosabe",
  "aap6a_aap6_noresponde"
)

# Resumen de valores perdidos (NA) para esas variables
na_resumen_necesidades <- sapply(data_filtrada[vars_necesidades], function(x) sum(is.na(x)))
na_resumen_necesidades  # No presenta valores nulos


```
```{r tabla estadisitca dificultades}

tabla_necesidades <- data_filtrada %>%
  select(all_of(vars_necesidades)) %>%
  pivot_longer(cols = everything(),
               names_to = "variable",
               values_to = "respuesta") %>%
  group_by(variable) %>%
  summarise(
    conteo_1 = sum(respuesta == 1, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(proporcion = conteo_1 /  nrow(data_filtrada)) %>%
  arrange(desc(proporcion))

tabla_necesidades



ggplot(tabla_necesidades, aes(x = reorder(variable, proporcion),
                              y = proporcion)) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = scales::percent(proporcion, accuracy = 0.1)),
            hjust = -0.1, size = 3.5) +
  coord_flip() +
  labs(
    title = "Necesidades reportadas por los hogares",
    x = "Necesidad",
    y = "Proporci칩n de hogares"
  ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     expand = expansion(mult = c(0, .1)))


```
```{r Cruce necesidades vs tiempo residencia}


## Agrupamos las diferentes necesidades segun su tipo para facilitar el analisis
tabla_necesidades_agrupada <- data_filtrada %>%
  mutate(
    # 1. Medios de vida y econom칤a
    grupo_medios = if_any(c(aap6a_aap6_empleo,
                            aap6a_aap6_deudas,
                            aap6a_aap6_semillas,
                            aap6a_aap6_asistencia_tec), ~ .x == 1),
    
    # 2. Vivienda y servicios b치sicos
    grupo_vivienda = if_any(c(aap6a_aap6_alojamiento,
                              aap6a_aap6_agua_med,
                              aap6a_aap6_servicios_san,
                              aap6a_aap6_transporte,
                              aap6a_aap6_comunicacion), ~ .x == 1),
    
    # 3. Alimentaci칩n y art칤culos b치sicos
    grupo_alimentos = if_any(c(aap6a_aap6_comida,
                               aap6a_aap6_articulos_hig,
                               aap6a_aap6_articulos_hog), ~ .x == 1),
    
    # 4. Salud y bienestar
    grupo_salud = if_any(c(aap6a_aap6_atencion_med,
                           aap6a_aap6_medicamentos,
                           aap6a_aap6_apoyo_psico), ~ .x == 1),
    
    # 5. Protecci칩n y educaci칩n
    grupo_proteccion = if_any(c(aap6a_aap6_educ,
                                aap6a_aap6_apoyo_psicolegal), ~ .x == 1),
    
    # 6. No clasificable
    grupo_noclas = if_any(c(aap6a_aap6_otro,
                            aap6a_aap6_ninguno,
                            aap6a_aap6_nosabe,
                            aap6a_aap6_noresponde), ~ .x == 1)
  ) 

## Resumen de tipo de necesidad
resumen_necesidades <- tabla_necesidades_agrupada %>%
  summarise(
    `Medios de vida y econom칤a`   = sum(grupo_medios, na.rm = TRUE),
    `Vivienda y servicios b치sicos`= sum(grupo_vivienda, na.rm = TRUE),
    `Alimentaci칩n y art칤culos b치sicos` = sum(grupo_alimentos, na.rm = TRUE),
    `Salud y bienestar`           = sum(grupo_salud, na.rm = TRUE),
    `Protecci칩n y educaci칩n`      = sum(grupo_proteccion, na.rm = TRUE),
    `No clasificable`             = sum(grupo_noclas, na.rm = TRUE),
    total_hogares                 = n()
  ) %>%
  pivot_longer(cols = -total_hogares,
               names_to = "grupo",
               values_to = "conteo") %>%
  mutate(proporcion = conteo / total_hogares) %>%
  arrange(desc(proporcion))

resumen_necesidades



# Generamos el cruce con el tiempo de residencia
necesidades_long <- tabla_necesidades_agrupada %>%
  select(meses_en_lugar,
         grupo_medios,
         grupo_vivienda,
         grupo_alimentos,
         grupo_salud,
         grupo_proteccion,
         grupo_noclas) %>%
  pivot_longer(
    cols = starts_with("grupo"),
    names_to = "grupo",
    values_to = "valor"
  ) %>%
  filter(valor == TRUE | valor == 1) %>%
  group_by(meses_en_lugar, grupo) %>%
  summarise(conteo = n(), .groups = "drop") %>%
  mutate(
    grupo = recode(grupo,
      grupo_medios     = "Medios de vida y econom칤a",
      grupo_vivienda   = "Vivienda y servicios b치sicos",
      grupo_alimentos  = "Alimentaci칩n y art칤culos b치sicos",
      grupo_salud      = "Salud y bienestar",
      grupo_proteccion = "Protecci칩n y educaci칩n",
      grupo_noclas     = "No clasificable"
    )
  )

necesidades_long


# Gr치fico de l칤neas
ggplot(necesidades_long, aes(x = meses_en_lugar, y = conteo, color = grupo, group = grupo)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Evoluci칩n de las necesidades seg칰n tiempo de residencia",
    x = "Tiempo de residencia (meses)",
    y = "N칰mero de hogares",
    color = "Grupo de necesidad"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom"
  )

```

```{r Cruce necesidades vs hacinamiento}



# Pasamos a formato largo: hogares x necesidades
necesidades_hacinamiento <- tabla_necesidades_agrupada %>%
  select(hacinamiento,
         grupo_medios,
         grupo_vivienda,
         grupo_alimentos,
         grupo_salud,
         grupo_proteccion,
         grupo_noclas) %>%
  pivot_longer(
    cols = starts_with("grupo"),
    names_to = "grupo",
    values_to = "valor"
  ) %>%
  filter(valor == TRUE | valor == 1) %>%
  group_by(hacinamiento, grupo) %>%
  summarise(conteo = n(), .groups = "drop") %>%
  mutate(
    grupo = recode(grupo,
      grupo_medios     = "Medios de vida y econom칤a",
      grupo_vivienda   = "Vivienda y servicios b치sicos",
      grupo_alimentos  = "Alimentaci칩n y art칤culos b치sicos",
      grupo_salud      = "Salud y bienestar",
      grupo_proteccion = "Protecci칩n y educaci칩n",
      grupo_noclas     = "No clasificable"
    )
  )

# Ordenar dentro de cada categor칤a de hacinamiento
necesidades_hacinamiento <- necesidades_hacinamiento %>%
  group_by(hacinamiento) %>%
  arrange(desc(conteo), .by_group = TRUE)

necesidades_hacinamiento


ggplot(necesidades_hacinamiento, aes(x = grupo, y = conteo, fill = grupo)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ hacinamiento, scales = "free_y") +
  labs(
    title = "Necesidades m치s frecuentes seg칰n tipo de hacinamiento",
    x = "Grupo de necesidad",
    y = "N칰mero de hogares"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 11, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 7), # m치s peque침o
    axis.title.x = element_text(margin = margin(t = 10))
  )

```


## Exploracion a nivel de las personas


```{r Corte de variables por medios de vida e Integraci칩n}

vars_mediosvida <- c(
  "miembros21",  # Tiempo dedicado 
  "miembros22",  # Horas trabajadas
  "miembros23",  # Trabajaria mas
  "miembros23a",  # quiere trabajar mas 
  "miembros30",  # Cuenta con contrato formal
  "miembros30b",   # Seguridad social en salud
  "miembros31a",  # Seguridad social pension
  "miembros21b",  # Rango de ingresos
  "miembros24a",  # Reporto dificultades para encontrar trabajo
  "miembros24b_dificultades_nodocu",  ### Razones ####
  "miembros24b_dificultades_familia",
  "miembros24b_dificultades_discrimina",
  "miembros24b_dificultades_noconocimi",
  "miembros24b_dificultades_noempleo",
  "miembros24b_dificultades_noofertas",
  "miembros24b_dificultades_noexperiencia",
  "miembros24b_dificultades_otra",
  "miembros24b_nosabe",
  "miembros24b_noresponde" #############
)

# Resumen de valores perdidos (NA) en estas variables
na_resumen_mediosvida <- sapply(data_bogota[vars_mediosvida], function(x) sum(is.na(x)))
na_resumen_mediosvida



```
```{r Imputacion NAs}

vars_24b <- c(
  "miembros24b_dificultades_nodocu",
  "miembros24b_dificultades_familia",
  "miembros24b_dificultades_discrimina",
  "miembros24b_dificultades_noconocimi",
  "miembros24b_dificultades_noempleo",
  "miembros24b_dificultades_noofertas",
  "miembros24b_dificultades_noexperiencia",
  "miembros24b_dificultades_otra",
  "miembros24b_nosabe",
  "miembros24b_noresponde"
)

data_bogota <- data_bogota %>%
  rowwise() %>%
  mutate(
    across(all_of(vars_24b), ~ case_when(
      #En caso de que no haya reportado dificultades con miembros24a = no, no ha buscado empleo, no sabe
      miembros24a %in% c("no", "no ha buscado empleo", "no sabe") & is.na(.x) ~ 0,
      
      # Pero si respondio que si encontro dificultades (miembros24a = si) y hay al menos una de las variables igual a 1, se asume que el resto no ocurrieron
      miembros24a == "si" & any(c_across(all_of(vars_24b)) == 1, na.rm = TRUE) & is.na(.x) ~ 0,
      
      TRUE ~ .x
    ))
  ) %>%
  ungroup()

# Resumen de valores perdidos (NA) en estas variables
na_resumen_mediosvida <- sapply(data_bogota[vars_mediosvida], function(x) sum(is.na(x)))
na_resumen_mediosvida




```
```{r Tablas estadisiticas por variable}



vars_principales <- c(
  "miembros21",
  "miembros30",
  "miembros30b",
  "miembros31a",
  "miembros21b"
)


tabla_cruzada_miembros21 <- data_bogota %>%
  count(miembros21, meses_en_lugar) %>%
  pivot_wider(
    names_from = meses_en_lugar,
    values_from = n,
    values_fill = 0
  )

tabla_cruzada_miembros21


tabla_cruzada_miembros30 <- data_bogota %>%
  count(miembros30, meses_en_lugar) %>%
  pivot_wider(
    names_from = meses_en_lugar,
    values_from = n,
    values_fill = 0
  )
tabla_cruzada_miembros30


tabla_cruzada_miembros30b <- data_bogota %>%
  count(miembros30b, meses_en_lugar) %>%
  pivot_wider(
    names_from = meses_en_lugar,
    values_from = n,
    values_fill = 0
  )
tabla_cruzada_miembros30b

tabla_cruzada_miembros31a <- data_bogota %>%
  count(miembros31a, meses_en_lugar) %>%
  pivot_wider(
    names_from = meses_en_lugar,
    values_from = n,
    values_fill = 0
  )
tabla_cruzada_miembros31a


tabla_cruzada_miembros21b <- data_bogota %>%
  count(miembros21b, meses_en_lugar) %>%
  pivot_wider(
    names_from = meses_en_lugar,
    values_from = n,
    values_fill = 0
  )
tabla_cruzada_miembros21b




```
  
  
```{r sEGURIDAD SOCIAL A LO LARGO DEL TIEMPO}

library(gridExtra)

##### SALUD ######
p1 <- ggplot(data_bogota %>%
               filter(!is.na(miembros30b)) %>%
               count(meses_en_lugar, miembros30b) %>%
               mutate(miembros30b = str_wrap(miembros30b, width = 25)), # salto de l칤nea
             aes(x = meses_en_lugar, y = n, fill = miembros30b)) +
  geom_col(position = "dodge") +
  labs(
    title = "Acceso a seguridad social en salud",
    x = "Meses en el lugar",
    y = "N칰mero de hogares",
    fill = "Respuesta"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    plot.title = element_text(size = 12, face = "bold"),
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 8)
  )



##### PENSION ######
p2 <- ggplot(data_bogota %>%
               filter(!is.na(miembros31a)) %>%
               count(meses_en_lugar, miembros31a) %>%
               mutate(miembros31a = str_wrap(miembros31a, width = 25)), # salto de l칤nea
             aes(x = meses_en_lugar, y = n, fill = miembros31a)) +
  geom_col(position = "dodge") +
  labs(
    title = "Acceso a seguridad social en pensiones",
    x = "Meses en el lugar",
    y = "N칰mero de hogares",
    fill = "Respuesta"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    plot.title = element_text(size = 12, face = "bold"),
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 8)
  )

grid.arrange(p1, p2, ncol = 2)


```


```{r NIVEL DE INGRESO A LO LARGO DEL TIEMPO}

ggplot(data_bogota %>%
         filter(!is.na(miembros21b)) %>%
         count(meses_en_lugar, miembros21b) %>%
         mutate(miembros21b = str_wrap(miembros21b, width = 30)),  # ajusta ancho del texto
       aes(x = meses_en_lugar, y = n, fill = miembros21b)) +
  geom_col(position = "dodge", width = 0.8) +
  labs(
    title = "Rangos de ingresos mensuales",
    x = "Meses en el lugar",
    y = "N칰mero de hogares",
    fill = "Ingreso mensual"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 8),
    axis.text.x = element_text(angle = 30, hjust = 1)
  )

```

```{r COMPARACION POR DIFICULTADES}

vars_dificultades <- c(
  "miembros24b_dificultades_nodocu",
  "miembros24b_dificultades_familia",
  "miembros24b_dificultades_discrimina",
  "miembros24b_dificultades_noconocimi",
  "miembros24b_dificultades_noempleo",
  "miembros24b_dificultades_noofertas",
  "miembros24b_dificultades_noexperiencia",
  "miembros24b_dificultades_otra",
  "miembros24b_nosabe",
  "miembros24b_noresponde"
)


dificultades_long <- data_bogota %>%
  select(all_of(vars_dificultades)) %>%
  pivot_longer(cols = everything(),
               names_to = "dificultad",
               values_to = "valor") %>%
  filter(valor == 1)

# Para las dificultades agrupadas
cruce_dificultades <- data_bogota %>%
  select(meses_en_lugar, all_of(vars_dificultades)) %>%
  pivot_longer(cols = -meses_en_lugar,
               names_to = "dificultad",
               values_to = "valor") %>%
  filter(valor == 1) %>%
  count(meses_en_lugar, dificultad, name = "frecuencia") %>%
  pivot_wider(names_from = meses_en_lugar,
              values_from = frecuencia,
              values_fill = 0)

cruce_dificultades




ggplot(cruce_dificultades,
       aes(x = meses_en_lugar, y = frecuencia, fill = dificultad)) +
  geom_col(position = "dodge") +
  labs(
    title = "Dificultades reportadas seg칰n tiempo de permanencia",
    x = "Meses en el lugar",
    y = "N칰mero de hogares",
    fill = "Dificultad"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    legend.position = "bottom",
    legend.text = element_text(size = 8)
  )


```
```{r Grafico DIFICULTADES}



cruce_dificultades_long <- data_bogota %>%
  select(meses_en_lugar, all_of(vars_dificultades)) %>%
  pivot_longer(cols = -meses_en_lugar,
               names_to = "dificultad",
               values_to = "valor") %>%
  filter(valor == 1) %>%
  count(meses_en_lugar, dificultad, name = "frecuencia") %>%
  mutate(dificultad = str_wrap(dificultad, width = 25))  


ggplot(cruce_dificultades_long,
       aes(x = meses_en_lugar, y = frecuencia, fill = dificultad)) +
  geom_col(position = "dodge") +
  labs(
    title = "Dificultades reportadas seg칰n tiempo de permanencia",
    x = "Meses en el lugar",
    y = "N칰mero de hogares",
    fill = "Dificultad"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    legend.position = "bottom",
    legend.title = element_text(size = 8),   
    legend.text = element_text(size = 7)     
  ) +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))


```